[workspace]
members = [
    "apps/ca",
    "libs/config_loader",
    "libs/crl_cache",
    "libs/grpc",
    "libs/password",
    "xtask",
]
resolver = "2"
[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
config_loader = { version = "0.1.0", path = "./libs/config_loader" }
crl_cache = { version = "0.1.0", path = "./libs/crl_cache" }
grpc = { version = "0.1.0", path = "./libs/grpc" }
humantime = "2.2.0"
humantime-serde = "1.1.1"
once_cell = "1.21.3"
password = { version = "0.1.0", path = "./libs/password" }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", default-features = false }
tokio = { version = "1.43.0" }
tower-http = { version = "0.6.6", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
panic = "abort"
split-debuginfo = "packed"
