[package]
name = "ca"
version.workspace = true
edition.workspace = true

[dependencies]
actix-tls = { version = "3.4.0", features = ["openssl"] }
actix-web = { version = "4.11.0", features = ["openssl"] }
chrono = { workspace = true }
config_loader = { workspace = true }
crl_cache = { workspace = true }
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
grpc = { workspace = true, features = ["ca","crl-server"] }
humantime = { workspace = true }
humantime-serde = { workspace = true }
once_cell = { workspace = true }
openssl = { version = "0.10.72" }
openssl-sys = "0.9.109"
password = { workspace = true }
reqwest = { version = "0.12.20", features = ["json", "rustls-tls"] }
serde = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "macros", "chrono", "runtime-tokio","migrate"] }
tokio = { workspace = true, features = ["rt","macros","rt-multi-thread","fs"] }
tonic-async-interceptor = "0.13.0"
tower = "0.5.2"
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "CHM_CA"
path = "src/main.rs"
