[package]
name = "ca"
version.workspace = true
edition.workspace = true


[dependencies]
tokio = { version = "1.43.0", features = ["rt","macros","rt-multi-thread","fs"] }
actix-web = { version = "4.11.0", features = ["openssl"] }
openssl = { version = "0.10.72", features = ["vendored"] }
rpassword = "7.4.0"
directories = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
chrono = { version = "0.4.41", features = ["serde"] }
rsntp = "4.0.0"
grpc = { version = "0.1.0", path = "../../libs/grpc", features = ["ca"] }
config_loader = { version = "0.1.0", path = "../../libs/config_loader" }
sqlx = { version = "0.8.6", features = ["sqlite", "macros", "chrono", "runtime-tokio"], default-features = false }
once_cell = "1.21.3"
actix-tls = { version = "3.4.0", features = ["openssl"] }

[[bin]]
name = "CHM_CA"
path = "src/main.rs"
