[server]
host = "127.0.0.1"
port = 50052

[certificate]
rootca = "certs/rootCA.crt"
rootca_key = "certs/rootCA.key"
passphrase = ""
backend = "sqlite"
store_path = "certs/cert_store.db"
max_connections = 10
timeout = 10

[develop]
debug = true

[controller]
fingerprint = ""
