[package]
name = "api_server"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "CHM_API"
path = "src/bin/app.rs"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
actix-multipart = { workspace = true }
tracing-subscriber = { workspace = true }
